<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 Fundamentos Descriptivos | Series de Tiempo</title>
  <meta name="description" content="Capítulo 3 Fundamentos Descriptivos | Series de Tiempo" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 Fundamentos Descriptivos | Series de Tiempo" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 Fundamentos Descriptivos | Series de Tiempo" />
  
  
  

<meta name="author" content="Zaira Idaly Pizo Gurrute" />


<meta name="date" content="2025-04-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="pronóstico-de-suicidios-en-antioquia-2005-2022.html"/>
<link rel="next" href="holt_winter.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Series de Tiempo</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="pronóstico-de-suicidios-en-antioquia-2005-2022.html"><a href="pronóstico-de-suicidios-en-antioquia-2005-2022.html"><i class="fa fa-check"></i><b>2</b> Pronóstico de Suicidios en Antioquia (2005-2022)</a>
<ul>
<li class="chapter" data-level="2.1" data-path="pronóstico-de-suicidios-en-antioquia-2005-2022.html"><a href="pronóstico-de-suicidios-en-antioquia-2005-2022.html#justificación"><i class="fa fa-check"></i><b>2.1</b> Justificación</a></li>
<li class="chapter" data-level="2.2" data-path="pronóstico-de-suicidios-en-antioquia-2005-2022.html"><a href="pronóstico-de-suicidios-en-antioquia-2005-2022.html#por-qué-aplica-para-pronóstico-en-series-de-tiempo"><i class="fa fa-check"></i><b>2.2</b> ¿Por qué aplica para pronóstico en series de tiempo?</a></li>
<li class="chapter" data-level="2.3" data-path="pronóstico-de-suicidios-en-antioquia-2005-2022.html"><a href="pronóstico-de-suicidios-en-antioquia-2005-2022.html#valor-agregado-del-pronóstico"><i class="fa fa-check"></i><b>2.3</b> Valor agregado del pronóstico</a></li>
<li class="chapter" data-level="2.4" data-path="pronóstico-de-suicidios-en-antioquia-2005-2022.html"><a href="pronóstico-de-suicidios-en-antioquia-2005-2022.html#fuente-de-los-datos-y-permisos-de-uso"><i class="fa fa-check"></i><b>2.4</b> Fuente de los datos y permisos de uso</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="fundamentos.html"><a href="fundamentos.html"><i class="fa fa-check"></i><b>3</b> Fundamentos Descriptivos</a>
<ul>
<li class="chapter" data-level="3.1" data-path="fundamentos.html"><a href="fundamentos.html#exploracion-de-datos"><i class="fa fa-check"></i><b>3.1</b> Exploracion de Datos</a></li>
<li class="chapter" data-level="3.2" data-path="fundamentos.html"><a href="fundamentos.html#promedio-movil."><i class="fa fa-check"></i><b>3.2</b> Promedio Movil.</a></li>
<li class="chapter" data-level="3.3" data-path="fundamentos.html"><a href="fundamentos.html#rezagos-y-autocorrelación"><i class="fa fa-check"></i><b>3.3</b> Rezagos y autocorrelación</a></li>
<li class="chapter" data-level="3.4" data-path="fundamentos.html"><a href="fundamentos.html#estacionariedad-y-diferenciación"><i class="fa fa-check"></i><b>3.4</b> Estacionariedad y diferenciación</a></li>
<li class="chapter" data-level="3.5" data-path="fundamentos.html"><a href="fundamentos.html#transformación-box-cox"><i class="fa fa-check"></i><b>3.5</b> Transformación Box-Cox</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="holt_winter.html"><a href="holt_winter.html"><i class="fa fa-check"></i><b>4</b> Modelado con Holt Winters y Suavizante</a>
<ul>
<li class="chapter" data-level="4.1" data-path="holt_winter.html"><a href="holt_winter.html#metodologia-de-holt-winters"><i class="fa fa-check"></i><b>4.1</b> Metodologia de Holt Winters</a></li>
</ul></li>
<<<<<<< HEAD
<li class="chapter" data-level="4" data-path="Modelo_lineal_estacionariedad.html"><a href="Modelo_lineal_estacionariedad.html"><i class="fa fa-check"></i><b>4</b> Análisis Temporal: Modelos Lineales y Estacionariedad</a></li>
<li class="chapter" data-level="5" data-path="Prophet.html"><a href="Prophet.html"><i class="fa fa-check"></i><b>5</b> Aplicación del Modelo Prophet</a>
<ul>
<li class="chapter" data-level="5.1" data-path="Prophet.html"><a href="Prophet.html#justificación-regresiva-y-ajuste-estacionario-en-series-temporales"><i class="fa fa-check"></i><b>5.1</b> Justificación Regresiva y Ajuste Estacionario en Series Temporales</a></li>
</ul></li>
=======
<li class="chapter" data-level="5" data-path="Modelo_lineal_estacionariedad.html"><a href="Modelo_lineal_estacionariedad.html"><i class="fa fa-check"></i><b>5</b> Análisis Temporal: Modelos Lineales y Estacionariedad</a></li>
>>>>>>> c8d0ec3f0c4178bc477d328849ca25a4e4495198
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/zairapizo/SeriesTime" target="blank">Publicado con Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Series de Tiempo</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="fundamentos" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capítulo 3</span> Fundamentos Descriptivos<a href="fundamentos.html#fundamentos" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>Variables de la base de datos</strong></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="fundamentos.html#cb1-1" tabindex="-1"></a><span class="fu">colnames</span>(datos)</span></code></pre></div>
<pre><code>##  [1] &quot;nombremunicipio&quot;         &quot;codigomunicipio&quot;        
##  [3] &quot;ubicacion&quot;               &quot;nombreregion&quot;           
##  [5] &quot;codigoregion&quot;            &quot;anio&quot;                   
##  [7] &quot;causamortalidad&quot;         &quot;tipopoblacionobjetivo&quot;  
##  [9] &quot;numeropoblacionobjetivo&quot; &quot;numerocasos&quot;</code></pre>
<p><strong>3 primeros Registros de la base de datos</strong></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="fundamentos.html#cb3-1" tabindex="-1"></a><span class="fu">head</span>(datos,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 10
##   nombremunicipio codigomunicipio ubicacion      nombreregion codigoregion  anio
##   &lt;chr&gt;                     &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;               &lt;dbl&gt; &lt;dbl&gt;
## 1 Abejorral                  5002 POINT (-75.42… ORIENTE                 7  2005
## 2 Abriaquí                   5004 POINT (-76.06… OCCIDENTE               6  2005
## 3 Alejandría                 5021 POINT (-75.14… ORIENTE                 7  2005
## # ℹ 4 more variables: causamortalidad &lt;chr&gt;, tipopoblacionobjetivo &lt;chr&gt;,
## #   numeropoblacionobjetivo &lt;dbl&gt;, numerocasos &lt;dbl&gt;</code></pre>
<p><strong>número total de registros</strong></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="fundamentos.html#cb5-1" tabindex="-1"></a><span class="fu">nrow</span>(datos)</span></code></pre></div>
<pre><code>## [1] 2250</code></pre>
<div id="exploracion-de-datos" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Exploracion de Datos<a href="fundamentos.html#exploracion-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Se inicia con la exploracion del Dataset, asi como con el resumen estadistico</p>
<p><strong>Estructura del dataset</strong></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="fundamentos.html#cb7-1" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb7-2"><a href="fundamentos.html#cb7-2" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(datos), <span class="at">format =</span> <span class="st">&quot;markdown&quot;</span>)</span></code></pre></div>
<table>
<colgroup>
<col width="9%" />
<col width="9%" />
<col width="16%" />
<col width="7%" />
<col width="7%" />
<col width="3%" />
<col width="9%" />
<col width="13%" />
<col width="14%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">nombremunicipio</th>
<th align="right">codigomunicipio</th>
<th align="left">ubicacion</th>
<th align="left">nombreregion</th>
<th align="right">codigoregion</th>
<th align="right">anio</th>
<th align="left">causamortalidad</th>
<th align="left">tipopoblacionobjetivo</th>
<th align="right">numeropoblacionobjetivo</th>
<th align="right">numerocasos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Abejorral</td>
<td align="right">5002</td>
<td align="left">POINT (-75.427045 5.79145)</td>
<td align="left">ORIENTE</td>
<td align="right">7</td>
<td align="right">2005</td>
<td align="left">Suicidios</td>
<td align="left">Poblacion total</td>
<td align="right">20249</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left">Abriaquí</td>
<td align="right">5004</td>
<td align="left">POINT (-76.064563 6.63197)</td>
<td align="left">OCCIDENTE</td>
<td align="right">6</td>
<td align="right">2005</td>
<td align="left">Suicidios</td>
<td align="left">Poblacion total</td>
<td align="right">269</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Alejandría</td>
<td align="right">5021</td>
<td align="left">POINT (-75.141258 6.376923)</td>
<td align="left">ORIENTE</td>
<td align="right">7</td>
<td align="right">2005</td>
<td align="left">Suicidios</td>
<td align="left">Poblacion total</td>
<td align="right">3816</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Amagá</td>
<td align="right">5030</td>
<td align="left">POINT (-75.703216 6.04063)</td>
<td align="left">SUROESTE</td>
<td align="right">8</td>
<td align="right">2005</td>
<td align="left">Suicidios</td>
<td align="left">Poblacion total</td>
<td align="right">27155</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Amalfi</td>
<td align="right">5031</td>
<td align="left">POINT (-75.075028 6.907385)</td>
<td align="left">NORDESTE</td>
<td align="right">4</td>
<td align="right">2005</td>
<td align="left">Suicidios</td>
<td align="left">Poblacion total</td>
<td align="right">20525</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left">Andes</td>
<td align="right">5034</td>
<td align="left">POINT (-75.877699 5.655629)</td>
<td align="left">SUROESTE</td>
<td align="right">8</td>
<td align="right">2005</td>
<td align="left">Suicidios</td>
<td align="left">Poblacion total</td>
<td align="right">41591</td>
<td align="right">6</td>
</tr>
</tbody>
</table>
<p><strong>Se realiza la verificación de valores nulos por cada una de las variables que conforman la data.</strong></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="fundamentos.html#cb8-1" tabindex="-1"></a><span class="co"># Verificar valores nulos</span></span>
<span id="cb8-2"><a href="fundamentos.html#cb8-2" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(datos))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="fundamentos.html#cb10-1" tabindex="-1"></a><span class="co"># Verificar la cantidad de valores nulos por columna</span></span>
<span id="cb10-2"><a href="fundamentos.html#cb10-2" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(datos))</span></code></pre></div>
<pre><code>##         nombremunicipio         codigomunicipio               ubicacion 
##                       0                       0                       0 
##            nombreregion            codigoregion                    anio 
##                       0                       0                       0 
##         causamortalidad   tipopoblacionobjetivo numeropoblacionobjetivo 
##                       0                       0                       0 
##             numerocasos 
##                       0</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="fundamentos.html#cb12-1" tabindex="-1"></a>grafico_faltantes <span class="ot">&lt;-</span><span class="fu">md.pattern</span>(datos, <span class="at">rotate.names =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##  /\     /\
## {  `---&#39;  }
## {  O   O  }
## ==&gt;  V &lt;==  No need for mice. This data set is completely observed.
##  \  \|/  /
##   `-----&#39;</code></pre>
<p><img src="series-tiempo_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="fundamentos.html#cb14-1" tabindex="-1"></a><span class="co">#Construcción de la serie temporal</span></span>
<span id="cb14-2"><a href="fundamentos.html#cb14-2" tabindex="-1"></a></span>
<span id="cb14-3"><a href="fundamentos.html#cb14-3" tabindex="-1"></a>df <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="fundamentos.html#cb14-4" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-5"><a href="fundamentos.html#cb14-5" tabindex="-1"></a>    <span class="at">numerocasos =</span> <span class="fu">as.numeric</span>(numerocasos),</span>
<span id="cb14-6"><a href="fundamentos.html#cb14-6" tabindex="-1"></a>    <span class="at">numeropoblacionobjetivo =</span> <span class="fu">as.numeric</span>(numeropoblacionobjetivo),</span>
<span id="cb14-7"><a href="fundamentos.html#cb14-7" tabindex="-1"></a>    <span class="at">tasa_suicidios =</span> numerocasos <span class="sc">/</span> numeropoblacionobjetivo <span class="sc">*</span> <span class="dv">1000</span></span>
<span id="cb14-8"><a href="fundamentos.html#cb14-8" tabindex="-1"></a>  )</span>
<span id="cb14-9"><a href="fundamentos.html#cb14-9" tabindex="-1"></a></span>
<span id="cb14-10"><a href="fundamentos.html#cb14-10" tabindex="-1"></a></span>
<span id="cb14-11"><a href="fundamentos.html#cb14-11" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb14-12"><a href="fundamentos.html#cb14-12" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tasa_suicidios =</span> numerocasos <span class="sc">/</span> numeropoblacionobjetivo <span class="sc">*</span> <span class="dv">100000</span>)</span>
<span id="cb14-13"><a href="fundamentos.html#cb14-13" tabindex="-1"></a></span>
<span id="cb14-14"><a href="fundamentos.html#cb14-14" tabindex="-1"></a></span>
<span id="cb14-15"><a href="fundamentos.html#cb14-15" tabindex="-1"></a><span class="co"># Agrupar por año</span></span>
<span id="cb14-16"><a href="fundamentos.html#cb14-16" tabindex="-1"></a>serie_anual <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb14-17"><a href="fundamentos.html#cb14-17" tabindex="-1"></a>  <span class="fu">group_by</span>(anio) <span class="sc">%&gt;%</span></span>
<span id="cb14-18"><a href="fundamentos.html#cb14-18" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">tasa_promedio =</span> <span class="fu">mean</span>(tasa_suicidios, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb14-19"><a href="fundamentos.html#cb14-19" tabindex="-1"></a></span>
<span id="cb14-20"><a href="fundamentos.html#cb14-20" tabindex="-1"></a><span class="co"># Verificar la serie</span></span>
<span id="cb14-21"><a href="fundamentos.html#cb14-21" tabindex="-1"></a><span class="fu">print</span>(serie_anual)</span></code></pre></div>
<pre><code>## # A tibble: 18 × 2
##     anio tasa_promedio
##    &lt;dbl&gt;         &lt;dbl&gt;
##  1  2005         14.1 
##  2  2006          9.20
##  3  2007         14.3 
##  4  2008          8.40
##  5  2009         14.8 
##  6  2010          8.04
##  7  2011          8.67
##  8  2012         10.7 
##  9  2013          9.25
## 10  2014         12.4 
## 11  2015         16.1 
## 12  2016         10.1 
## 13  2017         14.7 
## 14  2018        148.  
## 15  2019         45.8 
## 16  2020         11.6 
## 17  2021         18.6 
## 18  2022         14.7</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="fundamentos.html#cb16-1" tabindex="-1"></a>suicidios_anuales <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="fundamentos.html#cb16-2" tabindex="-1"></a>  <span class="fu">group_by</span>(anio) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="fundamentos.html#cb16-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_suicidios =</span> <span class="fu">sum</span>(numerocasos, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb16-4"><a href="fundamentos.html#cb16-4" tabindex="-1"></a></span>
<span id="cb16-5"><a href="fundamentos.html#cb16-5" tabindex="-1"></a><span class="fu">ggplot</span>(suicidios_anuales, <span class="fu">aes</span>(<span class="at">x =</span> anio, <span class="at">y =</span> total_suicidios)) <span class="sc">+</span></span>
<span id="cb16-6"><a href="fundamentos.html#cb16-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;steelblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="fundamentos.html#cb16-7" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>) <span class="sc">+</span></span>
<span id="cb16-8"><a href="fundamentos.html#cb16-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Número anual de suicidios en Antioquia&quot;</span>,</span>
<span id="cb16-9"><a href="fundamentos.html#cb16-9" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Año&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Total de suicidios&quot;</span>)</span></code></pre></div>
<p><img src="series-tiempo_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>La serie muestra una tendencia creciente clara a partir de 2014, con un aumento sostenido en el número de casos de suicidio. Entre 2005 y 2013, los valores se mantienen relativamente estables,con pequeñas fluctuaciones. Desde 2014 se observa una aceleración en el crecimiento,con picos notables en 2018, 2021 y 2022.</p>
<p>Esto sugiere la presencia de una tendencia no estacionaria, lo que indica que el uso de técnicas como la diferenciación o modelado ARIMA es apropiado para pronóstico y análisis más avanzado.</p>
<p>La gráfica no evidencia patrones cíclicos repetitivos anuales, lo cual es esperable al trabajar con datos anuales.</p>
<p>Aunque hay un patrón creciente, se observan algunos retrocesos puntuales, como en 2020 (probablemente asociado al impacto de la pandemia).</p>
<p>Estos descensos temporales podrían representar factores exógenos o eventos sociales que afectaron los reportes o las causas de suicidio.</p>
<p>Estas irregularidades justifican el uso de métodos de suaviza miento como promedios móviles para atenuar las variaciones y destacar la tendencia.</p>
</div>
<div id="promedio-movil." class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Promedio Movil.<a href="fundamentos.html#promedio-movil." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Promedio móvil del número de suicidios por año en Antioquia (2005–2022)</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="fundamentos.html#cb17-1" tabindex="-1"></a><span class="co">#Promedio móvil</span></span>
<span id="cb17-2"><a href="fundamentos.html#cb17-2" tabindex="-1"></a>suicidios_anuales <span class="ot">&lt;-</span> suicidios_anuales <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="fundamentos.html#cb17-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">promedio_movil =</span> zoo<span class="sc">::</span><span class="fu">rollmean</span>(total_suicidios, <span class="at">k =</span> <span class="dv">3</span>, <span class="at">fill =</span> <span class="cn">NA</span>))</span>
<span id="cb17-4"><a href="fundamentos.html#cb17-4" tabindex="-1"></a></span>
<span id="cb17-5"><a href="fundamentos.html#cb17-5" tabindex="-1"></a><span class="fu">ggplot</span>(suicidios_anuales, <span class="fu">aes</span>(<span class="at">x =</span> anio)) <span class="sc">+</span></span>
<span id="cb17-6"><a href="fundamentos.html#cb17-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> total_suicidios), <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="fundamentos.html#cb17-7" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> promedio_movil), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-8"><a href="fundamentos.html#cb17-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Promedio móvil de suicidios (k = 3)&quot;</span>,</span>
<span id="cb17-9"><a href="fundamentos.html#cb17-9" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Número de suicidios&quot;</span>)</span></code></pre></div>
<p><img src="series-tiempo_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>El anterior gráfico presenta el promedio móvil del número de suicidios por año en Antioquia desde 2005, utilizando una ventana de suavizamiento de k=3.</p>
<p>De las cual se puede describir lo siguiente:</p>
<p>La línea gris representa los datos anuales reales de suicidios.</p>
<p>La línea azul corresponde al promedio móvil, que suaviza las fluctuaciones anuales para destacar la tendencia general.</p>
<p>Entre 2005 y 2013, el número de suicidios se mantuvo relativamente estable.</p>
<p>A partir de 2014, se observa una tendencia creciente clara, que se intensifica progresivamente hasta 2022.</p>
<p>El promedio móvil permite visualizar un crecimiento sostenido, especialmente desde 2015 en adelante.</p>
<p>Puedo deducir algunas interpretaciones como que el aumento continuo podría estar relacionado con factores estructurales como problemas de salud mental, desigualdades sociales, impactos económicos o, en los años más recientes, efectos derivados de la pandemia.</p>
</div>
<div id="rezagos-y-autocorrelación" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Rezagos y autocorrelación<a href="fundamentos.html#rezagos-y-autocorrelación" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="fundamentos.html#cb18-1" tabindex="-1"></a>ts_suicidios <span class="ot">&lt;-</span> <span class="fu">ts</span>(suicidios_anuales<span class="sc">$</span>total_suicidios, <span class="at">start =</span> <span class="fu">min</span>(suicidios_anuales<span class="sc">$</span>anio), <span class="at">frequency =</span> <span class="dv">1</span>)</span>
<span id="cb18-2"><a href="fundamentos.html#cb18-2" tabindex="-1"></a></span>
<span id="cb18-3"><a href="fundamentos.html#cb18-3" tabindex="-1"></a><span class="co"># Autocorrelación</span></span>
<span id="cb18-4"><a href="fundamentos.html#cb18-4" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">ggAcf</span>(ts_suicidios) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Función de Autocorrelación (ACF)&quot;</span>)</span></code></pre></div>
<p><img src="series-tiempo_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="fundamentos.html#cb19-1" tabindex="-1"></a><span class="co"># Descomposición</span></span>
<span id="cb19-2"><a href="fundamentos.html#cb19-2" tabindex="-1"></a><span class="co"># Si tuvieras frecuencia mensual: frequency = 12</span></span>
<span id="cb19-3"><a href="fundamentos.html#cb19-3" tabindex="-1"></a><span class="co">#decomposicion &lt;- decompose(ts_suicidios, type = &quot;additive&quot;)</span></span>
<span id="cb19-4"><a href="fundamentos.html#cb19-4" tabindex="-1"></a><span class="co">#plot(decomposicion)</span></span></code></pre></div>
<p>Interpretación de la Función de Autocorrelación (ACF)</p>
<p>Se observa una autocorrelación positiva y significativa en los primeros rezagos:</p>
<p>Rezago 1: aproximadamente 0.75</p>
<p>Rezago 2: aproximadamente 0.60</p>
<p>Rezago 3: ligeramente superior a 0.45</p>
<p>A partir del rezago 4, la autocorrelación disminuye progresivamente y cae dentro del intervalo de no significancia (delimitado por las líneas azules en el gráfico).</p>
<p>Esto indica que los valores actuales del número de suicidios están fuertemente correlacionados con los valores registrados en los últimos 1 a 3 años.</p>
<p>Conclusiones:</p>
<p>Existe una dependencia temporal significativa, especialmente a corto plazo.</p>
<p>La estructura de autocorrelación sugiere que un modelo autoregresivo simple, como AR(1) o AR(2), podría ser adecuado para capturar la dinámica de la serie.</p>
<p>No se identifican patrones de estacionalidad, ya que no se observan picos regulares a intervalos fijos (por ejemplo, cada 12 rezagos, como sería típico en series mensuales con estacionalidad anual).</p>
</div>
<div id="estacionariedad-y-diferenciación" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Estacionariedad y diferenciación<a href="fundamentos.html#estacionariedad-y-diferenciación" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Test de Dickey-Fuller Aumentado (ADF)</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="fundamentos.html#cb20-1" tabindex="-1"></a><span class="fu">adf.test</span>(ts_suicidios)  <span class="co"># Prueba de Dickey-Fuller aumentada</span></span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  ts_suicidios
## Dickey-Fuller = -0.41096, Lag order = 2, p-value = 0.9788
## alternative hypothesis: stationary</code></pre>
<p>Resultado del test ADF:</p>
<p>Estadístico Dickey-Fuller: –0.41096</p>
<p>Orden de rezago utilizado: 2</p>
<p>Valor p: 0.9788</p>
<p>Hipótesis alternativa: la serie es estacionaria</p>
<p>Interpretación:</p>
<p>El valor p obtenido es 0.9788, muy superior al nivel de significancia típico (0.05).</p>
<p>Por lo tanto, no se rechaza la hipótesis nula del test ADF, que plantea que la serie tiene una raíz unitaria (es decir, no es estacionaria).</p>
<p>Esto implica que la serie ts_suicidios no es estacionaria, lo cual sugiere que:</p>
<p>Puede haber tendencias o patrones temporales no constantes.</p>
<p>No es adecuada para modelos que requieren estacionariedad (como ARIMA) sin transformación previa.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="fundamentos.html#cb22-1" tabindex="-1"></a><span class="co"># SComo no es estacionaria, se aplica diferenciación</span></span>
<span id="cb22-2"><a href="fundamentos.html#cb22-2" tabindex="-1"></a>ts_diff <span class="ot">&lt;-</span> <span class="fu">diff</span>(ts_suicidios)</span>
<span id="cb22-3"><a href="fundamentos.html#cb22-3" tabindex="-1"></a></span>
<span id="cb22-4"><a href="fundamentos.html#cb22-4" tabindex="-1"></a><span class="fu">plot</span>(ts_diff, <span class="at">main =</span> <span class="st">&quot;Serie diferenciada&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Diferencia de suicidios&quot;</span>)</span></code></pre></div>
<p><img src="series-tiempo_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>La gráfica anterior muestra las diferencias anuales en el número de suicidios, lo que permite analizar el comportamiento de los cambios interanuales.</p>
<p>En comparación con la serie original, podemos| obseravr que el comportamiento ahora es más estable, y se ha eliminado la tendencia creciente previamente observada.</p>
<p>No obstante, se evidencian fluctuaciones amplias en ciertos periodos, especialmente después de 2014, lo que podría reflejar cambios estructurales o eventos atípicos en esos años.</p>
<p>A pesar de estas variaciones, no se aprecia una tendencia sostenida en las diferencias, lo que sugiere que la serie podría haberse estacionarizado tras aplicar la primera diferencia.</p>
<p>La ausencia de estacionalidad sugiere que no es necesario aplicar técnicas de descomposición estacional ni modelos SARIMA.</p>
<p>Al tratarse de una serie anual, la estacionalidad no es relevante. El análisis debe centrarse en la tendencia y posibles componentes cíclicos de largo plazo.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="fundamentos.html#cb23-1" tabindex="-1"></a><span class="fu">adf.test</span>(ts_diff)  <span class="co"># Verifica estacionariedad después</span></span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  ts_diff
## Dickey-Fuller = -2.2107, Lag order = 2, p-value = 0.4921
## alternative hypothesis: stationary</code></pre>
<p>Resultados del Test de Dickey-Fuller Aumentado (ADF)</p>
<p>Al aplicar el test ADF a la serie diferenciada cuyo objetivo era evaluar su estacionariedad. Lo cual genera los siguientes resultados:</p>
<p>Estadístico ADF: –2.2107</p>
<p>Orden de rezago: 2</p>
<p>Valor p: 0.4921</p>
<p>Hipótesis alternativa: la serie es estacionaria</p>
<p>Interpretación:</p>
<p>El valor p obtenido (0.4921) es significativamente mayor que el umbral común de significancia (0.05), por lo tanto, no se rechaza la hipótesis nula de no estacionariedad. Esto sugiere que, incluso después de aplicar una primera diferenciación, la serie aún no cumple con los criterios estadísticos de estacionariedad según el test ADF.</p>
</div>
<div id="transformación-box-cox" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Transformación Box-Cox<a href="fundamentos.html#transformación-box-cox" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="fundamentos.html#cb25-1" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> <span class="fu">BoxCox.lambda</span>(ts_suicidios)</span>
<span id="cb25-2"><a href="fundamentos.html#cb25-2" tabindex="-1"></a>ts_boxcox <span class="ot">&lt;-</span> <span class="fu">BoxCox</span>(ts_suicidios, lambda)</span>
<span id="cb25-3"><a href="fundamentos.html#cb25-3" tabindex="-1"></a></span>
<span id="cb25-4"><a href="fundamentos.html#cb25-4" tabindex="-1"></a><span class="fu">autoplot</span>(ts_boxcox) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Serie transformada con Box-Cox&quot;</span>)</span></code></pre></div>
<p><img src="series-tiempo_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="pronóstico-de-suicidios-en-antioquia-2005-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="holt_winter.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["series-tiempo.pdf", "series-tiempo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
